export const WS_EVENT_UPDATED = 'WS_EVENT_UPDATED';
export const WS_EVENT_DELETED = 'WS_EVENT_DELETED';
export const WS_USER_LEAVE_EVENT = 'WS_USER_LEAVE_EVENT';
export const WS_USER_REMOVED_FROM_EVENT = 'WS_USER_REMOVED_FROM_EVENT';
export const WS_USER_INVITED_TO_EVENT = 'WS_USER_INVITED_TO_EVENT';
